### ISSUE TITLE
Dead VirtualGL link

### ISSUE THREAD

**Issue by inealey** [adamrehn/ue4-runtime#1]
Hi Adam, 

I could not build your virtualGL image due to a bad link.

Changing "https://svwh.dl.sourceforge.net/project/virtualgl/2.6.1/virtualgl_2.6.1_amd64.deb" to "https://sourceforge.net/projects/virtualgl/files/2.6.1/virtualgl_2.6.1_amd64.deb" worked for me.

Cheers!

**Comment by adamrehn** [comment]
Thanks for reporting this! Fix has been applied now.
