### ISSUE TITLE
Is it possible to support Ubuntu 16.04 (Xenial)? 

### ISSUE THREAD

**Issue by wthwlh** [adamrehn/ue4-runtime#2]
Hi, 

I wonder if it is possible to add additional tag for Ubuntu 16.04 Xenial. Since what I found this runtime image is bionic.

Thanks

**Comment by adamrehn** [comment]
Is there some particular reason why the older Ubuntu release is needed? The packages in the Ubuntu 16.04 repositories are frozen at software versions that are relatively old now, and the Ubuntu 18.04 base images [support more or less the same set of CUDA releases](https://hub.docker.com/r/nvidia/cudagl), so the newer OS version is usually the best choice for most use cases.

**Comment by milanow** [comment]
The other framework I have been used running in the same container (Sidecar Pattern) only supports Ubuntu 16.04 for now. It is hard to change/upgrade the framework and that's why I am trying to see if I could have a ue4-runtime:xeinal like image. Thanks.

**Comment by wthwlh** [comment]
The other framework I have been used running in the same container (Sidecar
Pattern) only supports Ubuntu 16.04 for now. It is hard to change/upgrade
the framework and that's why I am trying to see if I could have a
ue4-runtime:xeinal like image. Thanks.

Adam Rehn <notifications@github.com> 于2019年10月25日周五 上午12:38写道：

**Comment by wthwlh** [comment]
The other framework I have been used running in the same container (Sidecar
Pattern) only supports Ubuntu 16.04 for now. It is hard to change/upgrade
the framework and that's why I am trying to see if I could have a
ue4-runtime:xeinal like image. Thanks.

**Comment by adamrehn** [comment]
Support for multiple versions of Ubuntu has been implemented in commit 555f992 and the new image tags are [now live on Docker Hub](https://hub.docker.com/r/adamrehn/ue4-runtime). The Ubuntu 16.04 tags are prefixed with `adamrehn/ue4-runtime:16.04-` and include all of the same image variants available for Ubuntu 18.04.
