### ISSUE TITLE
Update base nvidia images used

### ISSUE THREAD

**Issue by Clockwork-Muse** [adamrehn/ue4-runtime#9]
[Nvidia now provides glvnd images for](https://hub.docker.com/r/nvidia/opengl/tags):

 - glvnd 1.1 and 1.2
 - Ubuntu 20.04

(PR request should be simple enough, but I didn't know the direction you wanted to take here)

**Comment by adamrehn** [comment]
Apologies for the delay in responding to this issue, I've been drowning in work over the past few months and progress on addressing my GitHub backlog has been frustratingly slow.

Looking at the [cudagl](https://hub.docker.com/r/nvidia/cudagl) image tags, it seems that all of the Ubuntu tags are now based on glvnd 1.2, so I guess the best option is probably to use 1.2 for all of the non-CUDA images to ensure consistency. I'll also add 20.04 tags and set the `latest` alias to point to 20.04.

**Comment by adamrehn** [comment]
The new tags are now pushed to Docker Hub.
